tutorial-proyecto-django/mysite/encuestas/urls.py
from django.urls import path

from . import views

app_name = "encuestas"
urlpatterns = [
    #/encuestas/
    path("", views.index, name="index"),
    #/encuestas/detalle/5/
    path("detalle/<str:question_id>/", views.detalle, name="detalle"),
    #/encuestas/5/resultado/
    path("<int:question_id>/resultado/", views.resultado, name="resultado"),
    #/encuestas/5/voto/
    path("<int:question_id>/voto/", views.voto, name="voto")
]

tutorial-proyecto-django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("encuestas/", include("encuestas.urls")),
    path('admin/', admin.site.urls),
]

tutorial-proyecto-django/mysite/encuestas/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return f"Pregunta: {self.question_text} Fecha: {self.pub_date}"
    
    def fue_publicacion_resiente(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return f"Opción: {self.choice_text} Votos: {self.votes} Question: {self.question}"

tutorial-proyecto-django/mysite/encuestas/views.py
#from django.http import HttpResponse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Question, Choice
#from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

# def index(request):
#     lista_ultimas_preguntas = Question.objects.order_by("-pub_date")[:5]
#     plantilla = loader.get_template("encuestas/index.html")
#     contexto = {
#         "lista_ultimas_preguntas": lista_ultimas_preguntas,
#     }
#     return HttpResponse(plantilla.render(contexto, request))

# def index(request):
    #return HttpResponse("Hola, mundo. Tú estas en el indice de encuestas.")

# def index(request):
    # lista_ultimas_preguntas = Question.objects.order_by("-pub_date")[:5]
    #salida = ", ".join([q.question_text for q in lista_ultimas_preguntas])
    #return HttpResponse(salida)

# def detalle(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("EL CUESTIONARIO NO EXISTE!")
#     return render(request, "encuestas/detalle.html", {"question": question})

    #return HttpResponse("Estas mirando los detalles de la pregunta %s." % question_id)

def index(request):
    lista_ultimas_preguntas = Question.objects.order_by("-pub_date")[:5]
    contexto = {"lista_ultimas_preguntas":lista_ultimas_preguntas}
    return render(request, "encuestas/index.html", contexto)

def detalle(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "encuestas/detalle.html", {"question": question})

def resultado(request, question_id):
    respuesta = "Estas viendo los resultados de la pregunta %s"
    return HttpResponse(respuesta % question_id)

def voto(request, question_id):
    pregunta = get_object_or_404(Question, pk=question_id)
    try:
        opcion_seleccionada = pregunta.choice_set.get(pk=request.POST["opcion"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request,"encuestas/detalle.html",{"question": pregunta,"error_message": "NO SELECCIONASTE UNA OPCIÓN",},)
    else:
        opcion_seleccionada.votes +=1
        opcion_seleccionada.save()
        #siempre usar HttpResponseRedirect despues de trabajar exitosamente con POST para evitar que los datos se publiquen dos veces si un usuario presiona el boton atras
        return HttpResponseRedirect(reverse("encuestas:resultado", args=(pregunta.id,)))
    #return HttpResponse("Estas votando en la pregunta %s" % question_id)

tutorial-proyecto-django/mysite/encuestas/templates/encuestas/detalle.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

<form action="{% url 'encuestas:voto' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

<form action="{% url 'encuestas:voto' question.id %}" method="post"> <!-- usa la etiqueta de plantilla url para general la URL a la que se enviara el formulario. 'encuestas:voto' nombre de la vista, question.id es le identificador de la pregunta -->
    {% csrf_token %} <!-- Implementacion de seguridad contra falsificacion de solicitud entre sitios web  -->
    <fieldset> <!-- para agrupar los elementos del formulario -->
        <legend><h1>{{question.question_text}}</h1></legend> <!-- legend proporciona un titulo para el grupo de campos y h1 para marcar el titulo principal de una pagina -->
        <!--CONTROL DE MENSAJE DE ERROR-->
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <!--MOSTRAR OPCIONES DE LA PREGUNTA CON BUCLE FOR-->
        {% for opcion in question.choice_set.all %}
            <input type="radio" name="opcion" id="opcion{{forloop.counter}}" value="{{opcion.id}}"> <!-- forloop.counter retorna el que iteracion del bucle se encuentra iniciando desde el 1 teniendo un valor inicial id="choice1"   -->
            <label for="opcion{{forloop.counter}}">{{opcion.choice_text}}</label><br> <!-- muestra el texto con la etiqueta lable al lado del imput de tipo radio -->
        {% endfor %}
    </fieldset>
    <input type="submit" value="Votar">
</form>

tutorial-proyecto-django/mysite/encuestas/templates/encuestas/index.html
{% if lista_ultimas_preguntas %}
    <ul>
    {% for question in lista_ultimas_preguntas %}
        <!-- <li><a href="/encuestas/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'encuestas:detalle' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Las encuestas no estan disponibles</p>
{% endif %}